# Generated by Django 4.1 on 2022-11-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartao',
            name='validade',
            field=models.CharField(max_length=6),
        ),
    ]
