# Generated by Django 4.1 on 2022-11-25 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_delete_conta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='cliente_pedido',
            new_name='cliente_de',
        ),
        migrations.RenameField(
            model_name='emprestimo',
            old_name='cliente_emprestou',
            new_name='cliente_para',
        ),
    ]
