# Generated by Django 4.1 on 2022-11-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_usuario_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateField(auto_now_add=True),
        ),
    ]
