# Generated by Django 4.1 on 2022-10-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_endereco_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='valor_emprestado',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
            preserve_default=False,
        ),
    ]
