# Generated by Django 4.1 on 2022-11-25 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_emprestimo_data_emprestimo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='data_emprestimo',
        ),
        migrations.RemoveField(
            model_name='fatura',
            name='data_pagamento',
        ),
        migrations.RemoveField(
            model_name='transacao',
            name='data_transacao',
        ),
    ]
