# Generated by Django 4.1 on 2022-10-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_emprestimo_valor_emprestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemprestimo',
            name='juros',
            field=models.IntegerField(),
        ),
    ]
