# Generated by Django 4.1 on 2022-11-25 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_emprestimo_data_emprestimo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='cliente_de',
        ),
        migrations.RemoveField(
            model_name='emprestimo',
            name='cliente_para',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='usuario_de',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_de', to='backend.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='usuario_para',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usuario_para', to='backend.usuario'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PagEmprestimo',
        ),
    ]
