# Generated by Django 4.1 on 2022-10-25 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_pagemprestimo_juros'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorito',
            name='possui_favorito',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='possui_favorito', to='backend.cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favorito',
            name='cliente_favoritado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cliente_favoritado', to='backend.cliente'),
        ),
    ]
