# Generated by Django 4.1 on 2022-11-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_emprestimo_cliente_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='saldo',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
