# Generated by Django 4.1 on 2022-11-22 14:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_usuario_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cartao',
        ),
        migrations.AddField(
            model_name='cartao',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagemprestimo',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
